name: dart_pubspec_licenses
description: A library to make it easy to extract OSS license information from Dart packages using pubspec.yaml
version: 3.0.4
homepage: https://github.com/espresso3389/flutter_oss_licenses/tree/master/packages/dart_pubspec_licenses
repository: https://github.com/espresso3389/flutter_oss_licenses

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  yaml: ^3.1.2
  path: ^1.9.0
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^5.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
